[buildPlans.InterMono]
family = "Inter Mono"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.InterMono.variants.design]
one = "base"
two = "straight-neck-serifless"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
zero = "oval-slashed"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
j = "flat-hook-serifed"
r = "hookless-serifed"
t = "flat-hook-short-neck2"
w = "straight-flat-top-serifless"
y = "straight-turn-serifless"
capital-eszet = "rounded-serifless"
long-s = "flat-hook-serifless"
lower-gamma = "straight"
lower-lambda = "tailed-turn"
lower-upsilon = "straight-serifless"
lower-chi = "semi-chancery-straight-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
asterisk = "hex-mid"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
at = "fourfold"
percent = "rings-continuous-slash"
lig-equal-chain = "without-notch"

[buildPlans.InterMono.variants.oblique]
a = "single-storey-serifless"
e = "rounded"
f = "flat-hook-tailed-crossbar-at-x-height"
cyrl-a = "single-storey-serifless"
number-sign = "upright"

[buildPlans.InterMono.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.InterMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.InterMono.weights.Medium]
shape = 520
menu = 500
css = 500

[buildPlans.InterMono.weights.SemiBold]
shape = 660
menu = 600
css = 600

[buildPlans.InterMono.weights.Bold]
shape = 825
menu = 700
css = 700

[buildPlans.InterMono.weights.ExtraBold]
shape = 1000
menu = 800
css = 800

[buildPlans.InterMono.widths.Normal]
shape = 620
menu = 5
css = "normal"

[buildPlans.InterMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.InterMono.slopes.Oblique]
angle = 9.4
shape = "oblique"
menu = "italic"
css = "italic"
